/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Views;

import Models.HoaDon;
import Models.HoaDonCT;
import Services.*;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vanlo
 */
public class ThanhtoanJDialog extends javax.swing.JDialog {

    /**
     * Creates new form ThanhtoanJDialog
     */
    IHoaDonService hoaDonService = new HoaDonService();
    List<HoaDon> hoaDons = new ArrayList<>();
    IHoaDonCTService hoaDonCTService = new HoaDonCTService();
    List<HoaDonCT> hoaDonCTs = new ArrayList<>();
    ISanPhamService sanPhamService = new SanPhamService();
    List<HoaDon> sanPhams = new ArrayList<>();
    DefaultTableModel _Model = new DefaultTableModel();
    long idHD;
    HoaDon hoaDon = new HoaDon();

    public ThanhtoanJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        txtTienGG.setEnabled(false);
        txtTienTT.setEnabled(false);
        txtTien1.setEnabled(false);
        loadTablehoaDon();
    }

    public void init() {
        setLocationRelativeTo(null);
        setTitle("Thanh toán");
    }

    private void loadTablehoaDon() {
        hoaDons = new ArrayList<>();
        List<HoaDon> hoaDon = new ArrayList<>();
        hoaDon = hoaDonService.getList();
        _Model = new DefaultTableModel();
        _Model = (DefaultTableModel) tbl_Donhang.getModel();
        _Model.setRowCount(0);
        for (int i = 0; i < hoaDon.size(); i++) {
            if (!hoaDon.get(i).isTinhTrangHD()) {
                hoaDons.add(hoaDon.get(i));
                int a = 0;
                hoaDonCTs = new ArrayList<>();
                hoaDonCTs = hoaDonCTService.getList(hoaDon.get(i));
                for (int j = 0; j < hoaDonCTs.size(); j++) {
                    a = a + hoaDonCTs.get(j).getGiaLM();
                }
                _Model.addRow(new Object[]{hoaDon.get(i).getKhachHang().getTenKH(), "chưa thanh toán", new SimpleDateFormat("dd/MM/yyyy").format(hoaDon.get(i).getNgayTT()), hoaDon.get(i).getTTGiamGia(), a - hoaDon.get(i).getTTGiamGia()});
            }
        }
    }

    private void loadTablehoaDonCT(List<HoaDonCT> hoaDonCT) {
        _Model = new DefaultTableModel();
        _Model = (DefaultTableModel) tbl_DonhangCT.getModel();
        _Model.setRowCount(0);
        long tien = 0;
        for (int i = 0; i < hoaDonCT.size(); i++) {
            tien = tien + hoaDonCT.get(i).getSoLuong() * hoaDonCT.get(i).getSanPham().getGiaBan();
            _Model.addRow(new Object[]{hoaDonCT.get(i).getSanPham().getTen(), hoaDonCT.get(i).getSoLuong(), hoaDonCT.get(i).getSoLuong() * hoaDonCT.get(i).getGiaLM()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_Donhang = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        j2 = new javax.swing.JLabel();
        j3 = new javax.swing.JLabel();
        j4 = new javax.swing.JLabel();
        txtTienTT = new javax.swing.JTextField();
        txtTienGG = new javax.swing.JTextField();
        txtTien1 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_DonhangCT = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("Thanh Toán");

        tbl_Donhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Khách Hàng", "Tình trang", "Ngày tạo HÐ", "tiền giảm giá", "tiền thanh toán"
            }
        ));
        tbl_Donhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_DonhangMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_Donhang);

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setText("Thanh Toán");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        j2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        j2.setText("tổng tiền");

        j3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        j3.setText("tiền giảm giá");

        j4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        j4.setText("tiền thanh toán");

        txtTienTT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtTienGG.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtTien1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTien1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTien1CaretUpdate(evt);
            }
        });
        txtTien1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTien1ActionPerformed(evt);
            }
        });

        tbl_DonhangCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tên", "số lượng", "giá"
            }
        ));
        tbl_DonhangCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_DonhangCTMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbl_DonhangCT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTienGG, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTien1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTienTT, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTien1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTienGG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTienTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(66, 66, 66)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_DonhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_DonhangMouseClicked
        int rowIndex = tbl_Donhang.getSelectedRow();
        if (rowIndex == -1) {
            return;
        }
        hoaDon = hoaDons.get(rowIndex);
        txtTienGG.setText(String.valueOf(hoaDon.getTTGiamGia()));
        if (!hoaDon.isTinhTrangHD()) {
            jButton2.setEnabled(true);
            jButton3.setEnabled(true);
        }
        hoaDonCTs.clear();
        hoaDonCTs = new ArrayList<>();
        hoaDonCTs = hoaDonCTService.getList(hoaDonService.getById(idHD));
        int TT = 0;
        for (int i = 0; i < hoaDonCTs.size(); i++) {

            TT = TT + (hoaDonCTs.get(i).getGiaLM() * hoaDonCTs.get(i).getSoLuong());
        }
        txtTien1.setText(String.valueOf(TT));
        txtTienTT.setText(String.valueOf(TT - hoaDon.getTTGiamGia()));
        idHD = hoaDons.get(rowIndex).getId();
        loadTablehoaDonCT(hoaDonCTs);

    }//GEN-LAST:event_tbl_DonhangMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        hoaDon = new HoaDon();
        txtTienGG.setText("");
        txtTienTT.setText("");
        txtTien1.setText("");
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        loadTablehoaDon();
        hoaDonCTs.clear();
        hoaDonCTs = new ArrayList<>();
        loadTablehoaDonCT(hoaDonCTs);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc muốn Thanh toán Hóa Đơn này ko?", "Thanh toán", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            hoaDon.setTinhTrangHD(true);
            if (hoaDonService.update(hoaDon) == true) {
                JOptionPane.showMessageDialog(this, "Thanh toán Hóa Đơn Thành công");
                hoaDon = new HoaDon();
                txtTienGG.setText("");
                txtTienTT.setText("");
                txtTien1.setText("");
                jButton2.setEnabled(false);
                jButton3.setEnabled(false);
                loadTablehoaDon();
                hoaDonCTs.clear();
                hoaDonCTs = new ArrayList<>();
                loadTablehoaDonCT(hoaDonCTs);
                return;
            }
            JOptionPane.showMessageDialog(this, "Thanh toán Hóa Đơn Chi Tiết Thất bại");
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtTien1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTien1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTien1ActionPerformed

    private void txtTien1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTien1CaretUpdate

    }//GEN-LAST:event_txtTien1CaretUpdate

    private void tbl_DonhangCTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_DonhangCTMouseClicked
        //        idHD = hoaDonCTs.get(rowIndex).getHoaDon().getId();
    }//GEN-LAST:event_tbl_DonhangCTMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThanhtoanJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThanhtoanJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThanhtoanJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThanhtoanJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ThanhtoanJDialog dialog = new ThanhtoanJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel j2;
    private javax.swing.JLabel j3;
    private javax.swing.JLabel j4;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tbl_Donhang;
    private javax.swing.JTable tbl_DonhangCT;
    private javax.swing.JTextField txtTien1;
    private javax.swing.JTextField txtTienGG;
    private javax.swing.JTextField txtTienTT;
    // End of variables declaration//GEN-END:variables
}
