/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Views;

import Models.HoaDon;
import Models.HoaDonCT;
import Services.*;
import java.text.ParseException;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vanlo
 */
public class ThongKeJDialog extends javax.swing.JDialog {

    /**
     * Creates new form ThanhtoanJDialog
     */
    IHoaDonService hoaDonService = new HoaDonService();
    List<HoaDon> hoaDons = new ArrayList<>();
    IHoaDonCTService hoaDonCTService = new HoaDonCTService();
    List<HoaDonCT> hoaDonCTs = new ArrayList<>();
    ISanPhamService sanPhamService = new SanPhamService();
    List<HoaDon> sanPhams = new ArrayList<>();
    DefaultTableModel _Model = new DefaultTableModel();
    SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
    long idHD;
    HoaDon hoaDon = new HoaDon();

    public ThongKeJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
        txtTienGG.setEnabled(false);
        txtTienTT.setEnabled(false);
        txtTien1.setEnabled(false);
        hoaDons.clear();
        hoaDons = new ArrayList<>();
        List<HoaDon> hoaDonList = hoaDonService.getList();
        for (int i = 0; i < hoaDonList.size(); i++) {
            if (hoaDonList.get(i).isTinhTrangHD()) {
                hoaDons.add(hoaDonList.get(i));
            }
        }
        loadTablehoaDon();
    }

    public void init() {
        setLocationRelativeTo(null);
        setTitle("thống kê");
    }

    private void loadTablehoaDon() {
        _Model = new DefaultTableModel();
        _Model = (DefaultTableModel) tbl_Donhang.getModel();
        _Model.setRowCount(0);
        for (int i = 0; i < hoaDons.size(); i++) {
            int a = 0;
            hoaDonCTs = new ArrayList<>();
            hoaDonCTs = hoaDonCTService.getList(hoaDons.get(i));
            for (int j = 0; j < hoaDonCTs.size(); j++) {
                a = a + hoaDonCTs.get(j).getGiaLM()*hoaDonCTs.get(j).getSoLuong();
            }
            _Model.addRow(new Object[]{hoaDons.get(i).getKhachHang().getTenKH(), "Đã thanh toán", new SimpleDateFormat("dd/MM/yyyy").format(hoaDons.get(i).getNgayTT()), hoaDons.get(i).getTTGiamGia(), a - hoaDons.get(i).getTTGiamGia()});

        }
    }

    private void loadTablehoaDonCT(List<HoaDonCT> hoaDonCT) {
        _Model = new DefaultTableModel();
        _Model = (DefaultTableModel) tbl_DonhangCT.getModel();
        _Model.setRowCount(0);
        long tien = 0;
        for (int i = 0; i < hoaDonCT.size(); i++) {
            tien = tien + hoaDonCT.get(i).getSoLuong() * hoaDonCT.get(i).getSanPham().getGiaBan();
            _Model.addRow(new Object[]{hoaDonCT.get(i).getSanPham().getTen(), hoaDonCT.get(i).getSoLuong(), hoaDonCT.get(i).getSoLuong() * hoaDonCT.get(i).getGiaLM(), hoaDonCT.get(i).getGiaLM()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_Donhang = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        j2 = new javax.swing.JLabel();
        j3 = new javax.swing.JLabel();
        j4 = new javax.swing.JLabel();
        txtTienTT = new javax.swing.JTextField();
        txtTienGG = new javax.swing.JTextField();
        txtTien1 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_DonhangCT = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        txtThang = new javax.swing.JComboBox<>();
        txtNam = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNgay = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNgay1 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtThang1 = new javax.swing.JComboBox<>();
        txtNam1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("thống kê");

        tbl_Donhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Khách Hàng", "Tình trang", "Ngày thanh toán", "tiền giảm giá", "tiền thanh toán"
            }
        ));
        tbl_Donhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_DonhangMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_Donhang);

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        j2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        j2.setText("tổng tiền");

        j3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        j3.setText("tiền giảm giá");

        j4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        j4.setText("tiền thanh toán");

        txtTienTT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtTienGG.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtTien1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTien1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTien1CaretUpdate(evt);
            }
        });
        txtTien1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTien1ActionPerformed(evt);
            }
        });

        tbl_DonhangCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên", "số lượng", "tông tiên", "giá lúc mua"
            }
        ));
        tbl_DonhangCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_DonhangCTMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbl_DonhangCT);

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setText("thống kê");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtThang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        txtNam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035" }));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setText("/");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("bắt đầu");

        txtNgay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNgay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("/");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setText("/");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("kết thúc:");

        txtNgay1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNgay1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setText("/");

        txtThang1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtThang1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        txtNam1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNam1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(j3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTienGG, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTien1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTienTT, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtNgay1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtThang1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtNam1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtThang, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTien1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTienGG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTienTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txtThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(txtNam, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNgay1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(txtThang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(txtNam1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_DonhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_DonhangMouseClicked
        int rowIndex = tbl_Donhang.getSelectedRow();
        if (rowIndex == -1) {
            return;
        }
        hoaDon = hoaDons.get(rowIndex);
        txtTienGG.setText(String.valueOf(hoaDon.getTTGiamGia()));
        hoaDonCTs.clear();
        hoaDonCTs = new ArrayList<>();
        hoaDonCTs = hoaDonCTService.getList(hoaDonService.getById(idHD));
        int TT = 0;
        for (int i = 0; i < hoaDonCTs.size(); i++) {

            TT = TT + (hoaDonCTs.get(i).getGiaLM() * hoaDonCTs.get(i).getSoLuong());
        }
        txtTien1.setText(String.valueOf(TT));
        txtTienTT.setText(String.valueOf(TT - hoaDon.getTTGiamGia()));
        idHD = hoaDons.get(rowIndex).getId();
        loadTablehoaDonCT(hoaDonCTs);

    }//GEN-LAST:event_tbl_DonhangMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        hoaDon = new HoaDon();
        txtTienGG.setText("");
        txtTienTT.setText("");
        txtTien1.setText("");
        loadTablehoaDon();
        hoaDonCTs.clear();
        hoaDonCTs = new ArrayList<>();
        List<HoaDon> hoaDonList = new ArrayList<>();
        hoaDonList = hoaDonService.getList();
        for (int i = 0; i < hoaDonList.size(); i++) {
            if (hoaDonList.get(i).isTinhTrangHD()) {
                hoaDons.add(hoaDonList.get(i));
            }
        }
        loadTablehoaDon();
        loadTablehoaDonCT(hoaDonCTs);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtTien1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTien1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTien1ActionPerformed

    private void txtTien1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTien1CaretUpdate

    }//GEN-LAST:event_txtTien1CaretUpdate

    private void tbl_DonhangCTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_DonhangCTMouseClicked
        //        idHD = hoaDonCTs.get(rowIndex).getHoaDon().getId();
    }//GEN-LAST:event_tbl_DonhangCTMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Date dateBD = null;
        Date dateKT = null;
        try {
            String dateB = txtNgay.getSelectedItem() + "/" + txtThang.getSelectedItem() + "/" + txtNam.getSelectedItem();
            dateBD = (Date) dateFormat.parse(dateB);
            String dateK = txtNgay1.getSelectedItem() + "/" + txtThang1.getSelectedItem() + "/" + txtNam1.getSelectedItem();
            dateKT = (Date) dateFormat.parse(dateK);
        } catch (ParseException e) {
            throw new RuntimeException(e);
        }
        hoaDons.clear();
        hoaDons = new ArrayList<>();
        List<HoaDon> hoaDonList = hoaDonService.getList();
        int T1 = 0;
        int TG = 0;
        for (int i = 0; i < hoaDonList.size(); i++) {
            if (hoaDonList.get(i).isTinhTrangHD()) {
                if (dateBD.compareTo(hoaDonList.get(i).getNgayTT()) <= 0 && dateKT.compareTo(hoaDonList.get(i).getNgayTT()) >= 0) {
                    TG = TG + hoaDonList.get(i).getTTGiamGia();
                    hoaDons.add(hoaDonList.get(i));
                    List<HoaDonCT> hoaDonCT = hoaDonCTService.getList(hoaDonService.getById(hoaDonList.get(i).getId()));
                    
                    for (int j = 0; j < hoaDonCT.size(); j++) {

                        T1 = T1 + (hoaDonCT.get(j).getGiaLM() * hoaDonCT.get(j).getSoLuong());
                    }
                }
            }
        }
        txtTien1.setText(String.valueOf(T1));
        txtTienGG.setText(String.valueOf(TG));
        txtTienTT.setText(String.valueOf(T1-TG));
        loadTablehoaDon();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThanhtoanJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThanhtoanJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThanhtoanJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThanhtoanJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ThongKeJDialog dialog = new ThongKeJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel j2;
    private javax.swing.JLabel j3;
    private javax.swing.JLabel j4;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tbl_Donhang;
    private javax.swing.JTable tbl_DonhangCT;
    private javax.swing.JComboBox<String> txtNam;
    private javax.swing.JComboBox<String> txtNam1;
    private javax.swing.JComboBox<String> txtNgay;
    private javax.swing.JComboBox<String> txtNgay1;
    private javax.swing.JComboBox<String> txtThang;
    private javax.swing.JComboBox<String> txtThang1;
    private javax.swing.JTextField txtTien1;
    private javax.swing.JTextField txtTienGG;
    private javax.swing.JTextField txtTienTT;
    // End of variables declaration//GEN-END:variables
}
